name: Auto label Pull Requests
on:
- pull_request

jobs:
  triage:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@70dbd623815438a6a851bd4a4ae141f82dd8a45b
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
