name: Auto label Pull Requests
on:
- pull_request

jobs:
  triage:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@ed55e8ab1fa323b4a53afb55132c065aa7a9f8f4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
