name: Auto label Pull Requests
on:
- pull_request

jobs:
  triage:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@c49f5acd80c2e9eea6ba380b8209695d5bc237dc
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
