name: Auto label Pull Requests
on:
- pull_request

jobs:
  triage:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@efde6da32c814aa4aee216cd4c31d833ef239eea
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
