name: (Dry run) Algolia

on:
  workflow_dispatch:

jobs:
  updateIndices:
    name: (Dry run) Update indices
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-node@094c36e88e2a3ffdf4d3a5bb935088ac39a46acc
      with:
        node-version: 14.x
    - name: cache node modules
      uses: actions/cache@35dd74a1a0674200316fa20212ce5036e0d9fc7f
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: npm ci
      run: npm ci
    - name: (Dry run) sync indices
      env:
        ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run sync-search-dry-run
