name: (Dry run) Algolia

on:
  workflow_dispatch:

jobs:
  updateIndices:
    name: (Dry run) Update indices
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@afe4af09a72596f47d806ee5f8b2674ec07fdc73
    - uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
      with:
        node-version: 14.x
    - name: cache node modules
      uses: actions/cache@6bbe742add91b3db4abf110e742a967ec789958f
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: npm ci
      run: npm ci
    - name: (Dry run) sync indices
      env:
        ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run sync-search-dry-run
