name: Ping staging apps

on:
  schedule:
    - cron:  "*/20 * * * *" # every twenty minutes

jobs:
  ping_staging_apps:
    name: Ping
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    env:
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
    steps:
    - uses: actions/checkout@afe4af09a72596f47d806ee5f8b2674ec07fdc73
    - name: npm ci
      run: npm ci
    - name: npm run build
      run: npm run build
    - name: Run script
      run: script/ping-staging-apps.js
