name: Public Repo Stale Check
on:
  schedule:
  - cron: "45 16 * * *"  # Run each day at 16:45 UTC / 8:45 PST

jobs:
  stale:
    if: github.repository == 'github/docs'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@2b58cc900ff11127b11b7b1c04121dca176bbd27
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }} 
        stale-pr-message: 'This PR is stale because it has been open 7 days with no activity and will be automatically closed in 3 days. To keep this PR open, update the PR by adding a comment or pushing a commit.'
        days-before-stale: 7
        days-before-close: 10
        stale-pr-label: 'stale'
