name: Triage new pull requests
on:
  pull_request:
    types: [reopened, opened]

jobs:
  triage_pulls:
    if: github.repository == 'github/docs'
    runs-on: ubuntu-latest

    steps:
    - name: Label new pull requests with 'triage'
      uses: rachmari/labeler@832d42ec5523f3c6d46e8168de71cd54363e3e2e
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        add-labels: "triage"
    - name: Triage to project board
      uses: rachmari/actions-add-new-issue-to-column@87a35587968c6914f03f43441c73b79739c42ae0
      with:
        action-token: ${{ secrets.GITHUB_TOKEN }}
        project-url: "https://github.com/github/docs/projects/1"
        column-name: "Triage"
